name: Robotframework
author: SWAG
description: Run automation tests
inputs:
  testsuites:
    description: Direct of tests to run
    required: true
    default: testsuites
  variables:
    description: File path to variables
    required: true
runs:
  using: docker
  image: docker://ghcr.io/robotframework-action:v0.2.0
  entrypoint: robot
  args:
  - -V
  - ${{ inputs.variables }}
  - ${{ inputs.testsuites }}
